# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright © 2026 Synaptics Incorporated.

"""Record fp32 ``decoder_kv`` calibration feeds for static int8 quantization.

Static (full-integer) quantization needs representative *activation* ranges, which for
``decoder_kv`` are model-internal tensors (inputs_embeds, per-layer self/cross KV, masks,
position_ids) — there is no downloadable preset for them. They are generated by running
the fp32 model over real audio (LibriSpeech ``dev-clean`` is the conventional corpus).

Rather than reimplement the streaming loop (and risk drift from the real pipeline), this
drives the *PyTorch* wrappers through the exact same orchestration as ``_inference.py`` by
wrapping each wrapper in a runner that mimics ``_LiteRTRunner``'s ``.infer()`` interface.
The decoder runner records every feed list it sees — at *every* decode step, not just
step 0, so the fuller-cache / larger-position ranges late in a sequence are covered.

Output: one ``.npz`` per decode step under ``<out_dir>/decoder_kv/``, each holding the
feed list as ``arg_000 .. arg_NNN`` in wrapper arg-order. The static-quant export loop
(see ``static_quant_plan.md`` step 3.2) globs these and feeds each through ``prepare_pt2e``.
"""

import argparse
import logging
from pathlib import Path

import numpy as np
import torch
from transformers import AutoConfig

from ...utils.logging import configure_logging
from .export import DecoderKVWrapper, StatefulFusedEncoderWrapper
from ._inference import MoonshineStreamingTFLite

logger = logging.getLogger("moonshine-tflite-calib")


def _load_model(model_size: str, hf_repo: str | None, models_dir: Path):
    """Load the fp32 PyTorch model (mirrors ``tflite_export._load_model`` but without
    importing that module, which pulls in ``litert_torch`` — unneeded for recording)."""
    from transformers import MoonshineStreamingForConditionalGeneration

    hf_repo = hf_repo or f"UsefulSensors/moonshine-streaming-{model_size}"
    local_dir = models_dir / hf_repo / "weights" / model_size
    if not (local_dir / "model.safetensors").exists():
        from huggingface_hub import snapshot_download
        logger.info("Downloading %s -> %s", hf_repo, local_dir)
        snapshot_download(
            repo_id=hf_repo, local_dir=str(local_dir), local_dir_use_symlinks=False,
            ignore_patterns=["*.msgpack", "*.h5", "flax_model*", "tf_model*"],
        )
    return MoonshineStreamingForConditionalGeneration.from_pretrained(
        str(local_dir), torch_dtype=torch.float32, local_files_only=True,
        attn_implementation="eager",
    ).eval()


class _TorchRunner:
    """Drives a PyTorch wrapper through the ``_LiteRTRunner`` interface the streaming
    orchestration expects: ``.infer(feeds)`` (numpy in, numpy out, wrapper arg/return
    order), plus ``.input_details`` (shapes) and ``.model_path`` (for sidecar tables)."""

    def __init__(self, module: torch.nn.Module, sample_args: tuple, model_path: Path):
        self._m = module.eval()
        self.model_path = Path(model_path)
        self._input_details = [
            {
                "name": f"serving_default_args_{i}",
                "index": i,
                "shape": tuple(int(d) for d in a.shape),
                "dtype": a.detach().cpu().numpy().dtype,
            }
            for i, a in enumerate(sample_args)
        ]

    @property
    def input_details(self):
        return self._input_details

    def infer(self, feeds: list[np.ndarray]) -> list[np.ndarray]:
        with torch.no_grad():
            tensors = [torch.from_numpy(np.ascontiguousarray(f)) for f in feeds]
            out = self._m(*tensors)
        if not isinstance(out, (tuple, list)):
            out = (out,)
        return [o.detach().cpu().numpy() for o in out]


class _RecordingTorchRunner(_TorchRunner):
    """A ``_TorchRunner`` that snapshots every feed list passed to ``.infer()``."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.records: list[list[np.ndarray]] = []

    def infer(self, feeds: list[np.ndarray]) -> list[np.ndarray]:
        self.records.append([np.array(f, copy=True) for f in feeds])
        return super().infer(feeds)


def _load_wav(path: Path) -> np.ndarray:
    """Load mono 16 kHz float32 audio, shape [1, num_samples]."""
    import soundfile as sf
    from scipy.signal import resample_poly

    data, sr = sf.read(str(path), dtype="float32")
    if data.ndim == 2:
        data = data.mean(axis=1)
    if sr != 16000:
        data = resample_poly(data, up=16000, down=sr).astype(np.float32)
    return data[np.newaxis, :]


def record_decoder_feeds(
    wavs: list[Path],
    model_size: str = "tiny",
    hf_repo: str | None = None,
    models_dir: str = "models",
    out_dir: str = "calib",
    chunk_len: int = 1280,
    max_audio_s: int = 5,
    max_tok_per_s: int = 6,
    max_tokens: int | None = None,
) -> int:
    """Run the fp32 PyTorch pipeline over ``wavs`` and dump per-step decoder feeds.

    Returns the number of decode-step records written.
    """
    models_dir = Path(models_dir)
    out_dir = Path(out_dir)
    dec_dir = out_dir / "decoder_kv"
    dec_dir.mkdir(parents=True, exist_ok=True)

    config = AutoConfig.from_pretrained(hf_repo or f"UsefulSensors/moonshine-streaming-{model_size}")
    hidden = int(config.hidden_size)
    dec_heads = getattr(config, "num_attention_heads", 8)
    num_kv_heads = getattr(config, "num_key_value_heads", 8)
    head_dim = hidden // dec_heads
    n_layers = getattr(config, "decoder_num_hidden_layers",
                       getattr(config, "num_hidden_layers", 6))
    num_samples = max_audio_s * 16_000
    n_max_tokens = max_audio_s * max_tok_per_s
    max_memory_len = num_samples // 320

    model = _load_model(model_size, hf_repo, models_dir)

    # Sidecar tables the orchestration loads via model_path.parent glob. Grab these
    # BEFORE building the wrappers: DecoderKVWrapper replaces decoder.pos_emb in place
    # with a ZeroEmbedding (no .weight), so reading it afterwards would fail.
    np.save(out_dir / "decoder_token_embeddings.npy",
            model.model.decoder.embed_tokens.weight.detach().cpu().numpy())
    np.save(out_dir / "adapter_pos_emb.npy",
            model.model.decoder.pos_emb.weight.detach().cpu().numpy())

    # ── fused_encoder wrapper + sample (drives the encoder side; not recorded) ──
    fused = StatefulFusedEncoderWrapper(model, chunk_len).eval()
    F, total_la = fused.F, fused.total_la
    embedder = model.model.encoder.embedder
    enc_hidden = int(embedder.linear.out_features)
    c1 = int(embedder.conv1.out_channels)
    left_ctxs = fused.encoder._left_ctx
    fe_sample = (
        torch.zeros(1, chunk_len),
        torch.zeros(1, enc_hidden, 4),
        torch.zeros(1, c1, 4),
        torch.zeros(1, total_la, enc_hidden),
        torch.zeros(1, F, enc_hidden),
        *[torch.zeros(1, lc, enc_hidden) for lc in left_ctxs],
    )

    # ── decoder_kv wrapper + sample (the one we record) ─────────────────────────
    decoder = DecoderKVWrapper(model, extract_embeddings=True, static_self_cache=True).eval()
    self_kv = [torch.zeros(1, num_kv_heads, n_max_tokens, head_dim) for _ in range(n_layers * 2)]
    cross_kv = [torch.zeros(1, num_kv_heads, max_memory_len, head_dim) for _ in range(n_layers * 2)]
    dec_sample = (
        torch.zeros(1, 1, hidden),
        *self_kv, *cross_kv,
        torch.zeros(1, num_kv_heads, 1, max_memory_len),  # cross_attn_bias
        torch.tensor([[0]], dtype=torch.int32),           # position_ids
        torch.zeros(1, 1, 1, n_max_tokens),               # self_attn_bias
    )

    fe_runner = _TorchRunner(fused, fe_sample, out_dir / "fused_encoder.pt")
    dec_runner = _RecordingTorchRunner(decoder, dec_sample, out_dir / "decoder_kv.pt")

    cfg = {
        "chunk_len": chunk_len, "feature_stride": F, "total_lookahead": total_la,
        "max_tokens": n_max_tokens, "max_memory_len": max_memory_len,
        "extract_embeddings": True,
    }
    runner = MoonshineStreamingTFLite(fe_runner, dec_runner, model_size, cfg)

    total = 0
    for ci, wav in enumerate(wavs):
        audio = _load_wav(Path(wav))
        dec_runner.records.clear()  # bound memory: keep only the current clip's feeds
        runner.run(audio, max_tokens=max_tokens)
        for si, feeds in enumerate(dec_runner.records):
            shard = dec_dir / f"clip{ci:03d}_step{si:03d}.npz"
            np.savez(shard, **{f"arg_{j:03d}": a for j, a in enumerate(feeds)})
        steps = len(dec_runner.records)
        dec_runner.records.clear()
        total += steps
        logger.info("clip %d/%d %-40s -> %d decode steps", ci + 1, len(wavs), Path(wav).name, steps)

    logger.info("Wrote %d decoder calibration records to %s", total, dec_dir)
    return total


def main():
    p = argparse.ArgumentParser(description="Record fp32 decoder_kv calibration feeds.")
    p.add_argument("-s", "--model-size", default="tiny", choices=["tiny", "small"])
    p.add_argument("--hf-repo", default=None)
    p.add_argument("--models-dir", default="models")
    p.add_argument("--out-dir", default="calib")
    p.add_argument("--wavs", nargs="+", required=True,
                   help="Audio files, or glob(s), e.g. 'librispeech/dev-clean/**/*.flac'")
    p.add_argument("--max-clips", type=int, default=None, help="Cap number of clips processed")
    p.add_argument("--shuffle", action="store_true",
                   help="Shuffle matched files before --max-clips (diverse speaker subset).")
    p.add_argument("--seed", type=int, default=0, help="Shuffle seed (default 0).")
    p.add_argument("--chunk-len", type=int, default=1280)
    p.add_argument("--input-seconds", type=int, default=5)
    p.add_argument("--tokens-per-sec", type=int, default=6)
    p.add_argument("--max-tokens", type=int, default=None)
    p.add_argument("--logging", default="INFO")
    args = p.parse_args()
    configure_logging(args.logging)

    import glob
    wavs: list[Path] = []
    for pat in args.wavs:
        hits = sorted(glob.glob(pat, recursive=True))
        wavs.extend(Path(h) for h in (hits or [pat]))
    if args.shuffle:
        import random
        random.Random(args.seed).shuffle(wavs)
    if args.max_clips:
        wavs = wavs[: args.max_clips]
    if not wavs:
        raise SystemExit("No audio files matched --wavs")

    record_decoder_feeds(
        wavs, model_size=args.model_size, hf_repo=args.hf_repo,
        models_dir=args.models_dir, out_dir=args.out_dir,
        chunk_len=args.chunk_len, max_audio_s=args.input_seconds,
        max_tok_per_s=args.tokens_per_sec, max_tokens=args.max_tokens,
    )


if __name__ == "__main__":
    main()
